#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

if data.get("password","") == "":
  exit(0)

username = data.get("username","")
password = data.get("password","")

config = {
  "DEFAULT_ADMIN_USERNAME": username,
  "DEFAULT_ADMIN_PASSWORD": password
}
agent.write_envfile('config.env', config)

# For later use and backup
with open('config.json', 'w') as cfp:
  cfp.write(json.dumps(data))