#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
SECRET_KEY = data.get("SECRET_KEY", "notsecretkey") 
BASE_URL = data.get("BASE_URL", "http://localhost:3000") 
DATABASE_URL = data.get("DATABASE_URL", "postgresql://postgres@postgres/planka") 
 
planka = { 
 "SECRET_KEY" : SECRET_KEY ,
 "BASE_URL" : BASE_URL ,
 "DATABASE_URL" : DATABASE_URL ,
} 
agent.write_envfile("planka.env", planka) 
