#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

try:
    with open('config.json', 'r') as cf:
        config = json.loads(cf.read())
        config["lets_encrypt"] = agent.get_route(os.environ['MODULE_ID']).get('lets_encrypt', False)
except:
    config = {"host": "", "lets_encrypt": False, "http2https": False}

json.dump(config, fp=sys.stdout)